language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
#- windows
cache:
  cargo: true
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco upgrade --no-progress -y pkgconfiglite make
        ;;
    esac
script:
- (cd fluidlite-sys && cargo test --release)
- (cd fluidlite-lib && cargo test --release)
- (cd fluidlite-lib && cargo test --release --features with-sf3)
- (cd fluidlite-lib && cargo test --release --features with-sf3,with-stb)
- (cd fluidlite && cargo test --release --features log)
jobs:
  allow_failures:
  - rust: nightly
  include:
  - stage: publish
    script:
    - (cd fluidlite-sys && cargo publish || true)
    - (cd fluidlite-lib && cargo publish || true)
    - (cd fluidlite && cargo publish || true)
    if: (type = push) && (tag =~ /^\d+\.\d+\.\d+/)
